//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Content
    {
        public Nullable<int> CourseID { get; set; }
        public int ContentId { get; set; }
        public string ContentType { get; set; }
        public string Url { get; set; }
    
        public virtual CreateCourse CreateCourse { get; set; }
    }
}
