//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace database
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class learnwithniteshsirEntities : DbContext
    {
        public learnwithniteshsirEntities()
            : base("name=learnwithniteshsirEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Account> Account { get; set; }
        public virtual DbSet<Category> Category { get; set; }
        public virtual DbSet<coursecontent> coursecontent { get; set; }
        public virtual DbSet<CreateCourse> CreateCourse { get; set; }
        public virtual DbSet<InstructorProfile> InstructorProfile { get; set; }
        public virtual DbSet<LoginAccess> LoginAccess { get; set; }
        public virtual DbSet<Message> Message { get; set; }
        public virtual DbSet<Roles> Roles { get; set; }
        public virtual DbSet<SocialMedia> SocialMedia { get; set; }
        public virtual DbSet<StudentCart> StudentCart { get; set; }
        public virtual DbSet<StudentProfile> StudentProfile { get; set; }
        public virtual DbSet<Content> Content { get; set; }
    }
}
