//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace database
{
    using System;
    using System.Collections.Generic;
    
    public partial class InstructorProfile
    {
        public Nullable<int> InstructorId { get; set; }
        public long InstructorPhoneNumber { get; set; }
        public string InstructorAddress { get; set; }
        public string InstructorAbout { get; set; }
        public Nullable<System.DateTime> Time { get; set; }
    
        public virtual Account Account { get; set; }
    }
}
