//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace database
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoginAccess
    {
        public int Id { get; set; }
        public string Emailid { get; set; }
        public string password { get; set; }
        public Nullable<System.DateTime> Logintime { get; set; }
    }
}
